/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWorkspaceWorkspaceSlugRouteImport } from './routes/_authenticated/workspace/$workspaceSlug'
import { Route as AuthenticatedWorkspaceWorkspaceSlugIndexRouteImport } from './routes/_authenticated/workspace/$workspaceSlug/index'
import { Route as AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRouteImport } from './routes/_authenticated/workspace/$workspaceSlug/my-issues/index'
import { Route as AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteImport } from './routes/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier'
import { Route as AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRouteImport } from './routes/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issues/index'
import { Route as AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRouteImport } from './routes/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/backlog/index'
import { Route as AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRouteImport } from './routes/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/active/index'
import { Route as AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRouteImport } from './routes/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issues/$issueIdentifier'
import { Route as AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRouteImport } from './routes/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issue/$issueIdentifier'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceWorkspaceSlugRoute =
  AuthenticatedWorkspaceWorkspaceSlugRouteImport.update({
    id: '/workspace/$workspaceSlug',
    path: '/workspace/$workspaceSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceSlugIndexRoute =
  AuthenticatedWorkspaceWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceSlugRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRoute =
  AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRouteImport.update({
    id: '/my-issues/',
    path: '/my-issues/',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceSlugRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute =
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteImport.update({
    id: '/team/$teamIdentifier',
    path: '/team/$teamIdentifier',
    getParentRoute: () => AuthenticatedWorkspaceWorkspaceSlugRoute,
  } as any)
const AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRoute =
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRouteImport.update(
    {
      id: '/issues/',
      path: '/issues/',
      getParentRoute: () =>
        AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute,
    } as any,
  )
const AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRoute =
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRouteImport.update(
    {
      id: '/backlog/',
      path: '/backlog/',
      getParentRoute: () =>
        AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute,
    } as any,
  )
const AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRoute =
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRouteImport.update(
    {
      id: '/active/',
      path: '/active/',
      getParentRoute: () =>
        AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute,
    } as any,
  )
const AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRoute =
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRouteImport.update(
    {
      id: '/issues/$issueIdentifier',
      path: '/issues/$issueIdentifier',
      getParentRoute: () =>
        AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute,
    } as any,
  )
const AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRoute =
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRouteImport.update(
    {
      id: '/issue/$issueIdentifier',
      path: '/issue/$issueIdentifier',
      getParentRoute: () =>
        AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/workspace/$workspaceSlug': typeof AuthenticatedWorkspaceWorkspaceSlugRouteWithChildren
  '/workspace/$workspaceSlug/': typeof AuthenticatedWorkspaceWorkspaceSlugIndexRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteWithChildren
  '/workspace/$workspaceSlug/my-issues/': typeof AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier/issue/$issueIdentifier': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier/issues/$issueIdentifier': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier/active/': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier/backlog/': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier/issues/': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/workspace/$workspaceSlug': typeof AuthenticatedWorkspaceWorkspaceSlugIndexRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteWithChildren
  '/workspace/$workspaceSlug/my-issues': typeof AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier/issue/$issueIdentifier': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier/issues/$issueIdentifier': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier/active': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier/backlog': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRoute
  '/workspace/$workspaceSlug/team/$teamIdentifier/issues': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/workspace/$workspaceSlug': typeof AuthenticatedWorkspaceWorkspaceSlugRouteWithChildren
  '/_authenticated/workspace/$workspaceSlug/': typeof AuthenticatedWorkspaceWorkspaceSlugIndexRoute
  '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteWithChildren
  '/_authenticated/workspace/$workspaceSlug/my-issues/': typeof AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRoute
  '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issue/$issueIdentifier': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRoute
  '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issues/$issueIdentifier': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRoute
  '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/active/': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRoute
  '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/backlog/': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRoute
  '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issues/': typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/workspace/$workspaceSlug'
    | '/workspace/$workspaceSlug/'
    | '/workspace/$workspaceSlug/team/$teamIdentifier'
    | '/workspace/$workspaceSlug/my-issues/'
    | '/workspace/$workspaceSlug/team/$teamIdentifier/issue/$issueIdentifier'
    | '/workspace/$workspaceSlug/team/$teamIdentifier/issues/$issueIdentifier'
    | '/workspace/$workspaceSlug/team/$teamIdentifier/active/'
    | '/workspace/$workspaceSlug/team/$teamIdentifier/backlog/'
    | '/workspace/$workspaceSlug/team/$teamIdentifier/issues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/workspace/$workspaceSlug'
    | '/workspace/$workspaceSlug/team/$teamIdentifier'
    | '/workspace/$workspaceSlug/my-issues'
    | '/workspace/$workspaceSlug/team/$teamIdentifier/issue/$issueIdentifier'
    | '/workspace/$workspaceSlug/team/$teamIdentifier/issues/$issueIdentifier'
    | '/workspace/$workspaceSlug/team/$teamIdentifier/active'
    | '/workspace/$workspaceSlug/team/$teamIdentifier/backlog'
    | '/workspace/$workspaceSlug/team/$teamIdentifier/issues'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/workspace/$workspaceSlug'
    | '/_authenticated/workspace/$workspaceSlug/'
    | '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier'
    | '/_authenticated/workspace/$workspaceSlug/my-issues/'
    | '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issue/$issueIdentifier'
    | '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issues/$issueIdentifier'
    | '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/active/'
    | '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/backlog/'
    | '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/$workspaceSlug': {
      id: '/_authenticated/workspace/$workspaceSlug'
      path: '/workspace/$workspaceSlug'
      fullPath: '/workspace/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/$workspaceSlug/': {
      id: '/_authenticated/workspace/$workspaceSlug/'
      path: '/'
      fullPath: '/workspace/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceSlugRoute
    }
    '/_authenticated/workspace/$workspaceSlug/my-issues/': {
      id: '/_authenticated/workspace/$workspaceSlug/my-issues/'
      path: '/my-issues'
      fullPath: '/workspace/$workspaceSlug/my-issues/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceSlugRoute
    }
    '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier': {
      id: '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier'
      path: '/team/$teamIdentifier'
      fullPath: '/workspace/$workspaceSlug/team/$teamIdentifier'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceSlugRoute
    }
    '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issues/': {
      id: '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issues/'
      path: '/issues'
      fullPath: '/workspace/$workspaceSlug/team/$teamIdentifier/issues/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute
    }
    '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/backlog/': {
      id: '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/backlog/'
      path: '/backlog'
      fullPath: '/workspace/$workspaceSlug/team/$teamIdentifier/backlog/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute
    }
    '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/active/': {
      id: '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/active/'
      path: '/active'
      fullPath: '/workspace/$workspaceSlug/team/$teamIdentifier/active/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute
    }
    '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issues/$issueIdentifier': {
      id: '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issues/$issueIdentifier'
      path: '/issues/$issueIdentifier'
      fullPath: '/workspace/$workspaceSlug/team/$teamIdentifier/issues/$issueIdentifier'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute
    }
    '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issue/$issueIdentifier': {
      id: '/_authenticated/workspace/$workspaceSlug/team/$teamIdentifier/issue/$issueIdentifier'
      path: '/issue/$issueIdentifier'
      fullPath: '/workspace/$workspaceSlug/team/$teamIdentifier/issue/$issueIdentifier'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute
    }
  }
}

interface AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteChildren {
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRoute
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRoute
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRoute
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRoute
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRoute
}

const AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteChildren: AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteChildren =
  {
    AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRoute:
      AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssueIssueIdentifierRoute,
    AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRoute:
      AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIssueIdentifierRoute,
    AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRoute:
      AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierActiveIndexRoute,
    AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRoute:
      AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierBacklogIndexRoute,
    AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRoute:
      AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierIssuesIndexRoute,
  }

const AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteWithChildren =
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteChildren,
  )

interface AuthenticatedWorkspaceWorkspaceSlugRouteChildren {
  AuthenticatedWorkspaceWorkspaceSlugIndexRoute: typeof AuthenticatedWorkspaceWorkspaceSlugIndexRoute
  AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute: typeof AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteWithChildren
  AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRoute: typeof AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRoute
}

const AuthenticatedWorkspaceWorkspaceSlugRouteChildren: AuthenticatedWorkspaceWorkspaceSlugRouteChildren =
  {
    AuthenticatedWorkspaceWorkspaceSlugIndexRoute:
      AuthenticatedWorkspaceWorkspaceSlugIndexRoute,
    AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRoute:
      AuthenticatedWorkspaceWorkspaceSlugTeamTeamIdentifierRouteWithChildren,
    AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRoute:
      AuthenticatedWorkspaceWorkspaceSlugMyIssuesIndexRoute,
  }

const AuthenticatedWorkspaceWorkspaceSlugRouteWithChildren =
  AuthenticatedWorkspaceWorkspaceSlugRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspaceSlugRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedWorkspaceWorkspaceSlugRoute: typeof AuthenticatedWorkspaceWorkspaceSlugRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedWorkspaceWorkspaceSlugRoute:
    AuthenticatedWorkspaceWorkspaceSlugRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
